Feat/home
sonishreyas/ripple-social pull request #2
Opened 2022-05-13 18:48 UTC by sonishreyas

# Change logs

- Added home page UI

2022-05-13 19:36 UTC, vidhi-thakur approved these changes
Code looks good, however, please confirm if we should be using `getElementById` code in React JS. Other than that, like the use of barrel exports, semantic tags and css variables

2022-05-13 19:36 UTC, vidhi-thakur commented on src/components/Home/NewPostModal.jsx
> +	// console.log(postState);
console log can be removed here

2022-05-13 19:36 UTC, vidhi-thakur commented on src/components/Toast/ToastPortal.jsx
> +		document.getElementById("toast-container")
I am not sure if this should be used here. Please confirm this with someone.

2022-05-13 19:36 UTC, vidhi-thakur commented on src/context/post-context.js
> +	// console.log(postState);
please remove

2022-05-13 19:36 UTC, vidhi-thakur commented on src/css/posts.css
> +  -moz-box-shadow: none;
nice 👍

2022-05-15 12:04 UTC, ravikumar0403 requested changes
app.css is not applied to your deployed site, I've mentioned the reason in the comments.
Login functionality is not working. Check these out

2022-05-15 12:04 UTC, ravikumar0403 commented on public/index.html
> +  <link rel="stylesheet" href="../src/css/app.css">
files in src directory get's minified and bundled at build time and those files are added to a build directory, the build directory is the only thing that is deployed, so any files that you import from external folders will not be available unless it is served over the internet. Here your app.css is not being imported in deployed version. 
import it in your `App.js`

2022-05-15 12:04 UTC, ravikumar0403 commented on src/components/Toast/ToastPortal.jsx
> +		document.getElementById("toast-container")
This is correct, that's how you use react portals.

2022-05-15 12:04 UTC, ravikumar0403 commented on src/custom-hooks/useToast.jsx
> +		notify();
As these are the default styles of your toast, you can pass it as a prop to the ToastContainer component itself. imo, this abstraction is redundant and also adds a limitation of using toast only inside a component or custom hook.

2022-05-15 12:04 UTC, ravikumar0403 commented on src/reducers/modal-reducer.js
> +				dismissChoice: payload.dismissChoice,
The key in the payload is the same as the key in the state, so you can just destructed payload to achieve the same result

2022-05-22 19:36 UTC, merged